INSERT INTO `categoria`(`cat_nombre`) VALUES ('Hogar');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Tecnologia');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Bebidas');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Comida');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Ropa');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Estudio');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Ferreteria');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Medicina');
INSERT INTO `producto`(`prod_descripcion`, `prod_nombre`, `prod_precio`, `prod_id_categoria`) VALUES ('aaaaaa','aaa',123,1);
INSERT INTO `producto`(`prod_descripcion`, `prod_nombre`, `prod_precio`, `prod_id_categoria`) VALUES ('cccccc','ccc',789,3);
INSERT INTO `producto`(`prod_descripcion`, `prod_nombre`, `prod_precio`, `prod_id_categoria`) VALUES ('dddddd','ddd',155 ,4);
INSERT INTO `producto`(`prod_descripcion`, `prod_nombre`, `prod_precio`, `prod_id_categoria`) VALUES ('eeeeee','eee',166,5);
INSERT INTO `persona`(`per_id`, `per_apellido`, `per_cedula`, `per_correo`, `per_direccion`, `per_nombre`, `per_sexo`, `per_telefono`) VALUES (1,'asdf','0107560419','gt618@gmail.com','sayauisi','morenos','Hombre','00000000');
INSERT INTO `usuario`(`usu_id`, `usu_calificacion`, `usu_contra_usuario`, `usu_estado` ,`usu_nombre_usuario`, `usu_per_id`) VALUES (1,'0','1234',true,'admin',1);