INSERT INTO `categoria`(`cat_nombre`) VALUES ('Hogar');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Tecnologia');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Bebidas');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Comida');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Ropa');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Estudio');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Ferreteria');
INSERT INTO `categoria`(`cat_nombre`) VALUES ('Medicina');
INSERT INTO `producto`(`prod_id`, `prod_descripcion`, `prod_nombre`, `prod_precio`, `prod_id_categoria`) VALUES (1,'aaaaaa','aaa',123,1);
INSERT INTO `producto`(`prod_id`, `prod_descripcion`, `prod_nombre`, `prod_precio`, `prod_id_categoria`) VALUES (2,'bbbbbb','bbb',345,2);
INSERT INTO `producto`(`prod_id`, `prod_descripcion`, `prod_nombre`, `prod_precio`, `prod_id_categoria`) VALUES (3,'cccccc','ccc',789,3);
INSERT INTO `producto`(`prod_id`, `prod_descripcion`, `prod_nombre`, `prod_precio`, `prod_id_categoria`) VALUES (4,'dddddd','ddd',155 ,4);
INSERT INTO `producto`(`prod_id`, `prod_descripcion`, `prod_nombre`, `prod_precio`, `prod_id_categoria`) VALUES (5,'eeeeee','eee',166,5);